version: 2.1
jobs:
  build:
    docker:
        - image: mariuscristian/numerous-requirements:1.0.1

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
                pip-dependency-file: requirements.txt
                pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          name: Tests
          command: |
            python3 -m pytest

orbs:
  python: circleci/python@1.3.2